"""Site-specific QUAM root and extensions for CS_4 (two-qubit + XY-driven tunable coupler).

``TunableCouplerWithXY`` composes the stock flux ``TunableCoupler`` (reused in place as ``z``)
with an ``XYDriveMW`` line so experiments can call ``pair.coupler.xy.play("cw")`` while
keeping ``apply_all_couplers_to_min`` working via delegated flux helpers on the wrapper.
"""

from __future__ import annotations

from typing import Optional, Union

from qm.qua import align, wait

from quam.core import quam_dataclass
from quam.components.quantum_components import QuantumComponent
from quam_builder.architecture.superconducting.components.tunable_coupler import TunableCoupler
from quam_builder.architecture.superconducting.components.xy_drive import XYDriveIQ, XYDriveMW
from quam_builder.architecture.superconducting.qubit import FluxTunableTransmon
from quam_builder.architecture.superconducting.qubit_pair.flux_tunable_transmon_pair import FluxTunableTransmonPair
from quam_builder.architecture.superconducting.qpu import FluxTunableQuam


@quam_dataclass
class TunableCouplerWithXY(QuantumComponent):
    """Flux tunable coupler plus a dedicated MW-FEM (or IQ) XY port.

    The existing ``z`` channel object is reused (same wiring references) so we do not
    duplicate LF FEM configuration generated by ``build_quam``.
    """

    id: Union[str, int]
    z: Optional[TunableCoupler] = None
    xy: Optional[Union[XYDriveMW, XYDriveIQ]] = None

    @property
    def name(self) -> str:
        return str(self.id)

    @property
    def flux_point(self):
        if self.z is None:
            raise AttributeError("Coupler has no flux (z) channel configured")
        return self.z.flux_point

    def to_decouple_idle(self):
        if self.z is not None:
            self.z.to_decouple_idle()

    def to_interaction_idle(self):
        if self.z is not None:
            self.z.to_interaction_idle()

    def to_arbitrary_idle(self):
        if self.z is not None:
            self.z.to_arbitrary_idle()

    def to_zero(self):
        if self.z is not None:
            self.z.to_zero()

    def set_dc_offset(self, offset):
        if self.z is not None:
            self.z.set_dc_offset(offset)

    def settle(self):
        if self.z is not None:
            self.z.settle()


@quam_dataclass
class FluxTunableTransmonPairXYCoupler(FluxTunableTransmonPair):
    """Same as upstream pair, but ``align`` / ``wait`` include both coupler MW and flux elements."""

    coupler: Optional[TunableCouplerWithXY] = None

    def _coupler_channel_names(self) -> list[str]:
        names: list[str] = []
        if not self.coupler:
            return names
        if self.coupler.z is not None:
            names.append(self.coupler.z.name)
        if self.coupler.xy is not None:
            names.append(self.coupler.xy.name)
        return names

    def _macro_compensation_channel_names(self) -> list[str]:
        channels: list[str] = []
        if "CZ" in self.macros and hasattr(self.macros["CZ"], "compensations"):
            for compensation in self.macros["CZ"].compensations:
                channels += [ch.name for ch in compensation["qubit"].channels.values()]
        return channels

    def _get_all_channel_names(self) -> list[str]:
        channels: list[str] = []
        for qubit in [self.qubit_control, self.qubit_target]:
            channels += [ch.name for ch in qubit.channels.values()]
        channels += self._coupler_channel_names()
        channels += self._macro_compensation_channel_names()
        return channels

    def align(self):
        align(*self._get_all_channel_names())

    def wait(self, duration):
        wait(duration, *self._get_all_channel_names())

    def to_mutual_idle(self):
        """Respect qubits that have no ``z`` line (e.g. fixed-frequency transmon)."""
        if getattr(self.qubit_control, "z", None) is not None:
            self.qubit_control.z.set_dc_offset(self.mutual_flux_bias[0])
        zt = getattr(self.qubit_target, "z", None)
        if zt is not None:
            zt.set_dc_offset(self.mutual_flux_bias[1])


@quam_dataclass
class Quam(FluxTunableQuam):
    """Root QUAM for superconducting calibrations on CS_4."""

    qubit_pair_type = FluxTunableTransmonPairXYCoupler

    def apply_all_flux_to_zero(self) -> None:
        """Like upstream, but skip qubits with no flux line (fixed-frequency transmons)."""
        for q in self.active_qubits:
            z = getattr(q, "z", None)
            if z is not None:
                z.to_zero()

    def set_all_fluxes(
        self,
        flux_point: str,
        target: Union[FluxTunableTransmon, FluxTunableTransmonPair, None] = None,
    ):
        """Set flux biases; tolerate active qubits without ``z`` (joint idle is global)."""
        if flux_point == "independent":
            assert isinstance(
                target, FluxTunableTransmon
            ), "Independent flux point is only supported for individual transmons"
        elif flux_point == "pairwise":
            assert isinstance(
                target, FluxTunableTransmonPair
            ), "Pairwise flux point is only supported for transmon pairs"

        target_bias = None
        if flux_point == "joint":
            self.apply_all_flux_to_joint_idle()
            if isinstance(target, FluxTunableTransmonPair):
                target_bias = target.mutual_flux_bias
            elif isinstance(target, FluxTunableTransmon) and getattr(target, "z", None) is not None:
                target_bias = target.z.joint_offset
        else:
            self.apply_all_flux_to_min()

        if flux_point == "independent":
            assert target is not None and target.z is not None
            target.z.to_independent_idle()
            target_bias = target.z.independent_offset

        elif flux_point == "pairwise":
            assert isinstance(target, FluxTunableTransmonPair)
            target.to_mutual_idle()
            target_bias = target.mutual_flux_bias

        if target is None:
            for q in self.qubits.values():
                z = getattr(q, "z", None)
                if z is not None:
                    z.settle()
                q.align()
        else:
            tz = getattr(target, "z", None)
            if tz is not None:
                tz.settle()
            target.align()

        return target_bias
