"""
This script is used to populate the quam generated by running generate_quam.py with initial values based on previous
calibrations or chip manufacturer specs and must be run prior to conducting the first experiment.
It is split according to the component to update (resonator, qubit xy drive, cavity drive) and allows the user to specify
the different frequencies and power involved. Other parameters are directly related to the control hardware such as
full_scale_power_dbm, band, upsampling_mode...
The last section is dedicated to adding pulses for the single qubit gates and setting the initial values for the
readout, saturation, and cavity pulses.
"""

########################################################################################################################
# %%                                             Import section
########################################################################################################################
import json
from pprint import pprint

import numpy as np
from qualang_tools.units import unit
from quam_builder.builder.superconducting.pulses import add_DragCosine_pulses
from quam_config import Quam

from quam.components.pulses import SquarePulse

########################################################################################################################
# %%                                 QUAM loading and auxiliary functions
########################################################################################################################
# Loads the QUAM
machine = Quam.load()
# Class containing tools to help handling units and conversions.
u = unit(coerce_to_integer=True)


def get_band(freq):
    """Determine the MW fem DAC band corresponding to a given frequency.

    Args:
        freq (float): The frequency in Hz.

    Returns:
        int: The Nyquist band number.
            - 1 if 50 MHz <= freq < 5.5 GHz
            - 2 if 4.5 GHz <= freq < 7.5 GHz
            - 3 if 6.5 GHz <= freq <= 10.5 GHz

    Raises:
        ValueError: If the frequency is outside the MW fem bandwidth [50 MHz, 10.5 GHz].
    """
    if 50e6 <= freq < 5.5e9:
        return 1
    elif 4.5e9 <= freq < 7.5e9:
        return 2
    elif 6.5e9 <= freq <= 10.5e9:
        return 3
    else:
        raise ValueError(f"The specified frequency {freq} Hz is outside of the MW fem bandwidth [50 MHz, 10.5 GHz]")


def closest_number(lst, target):
    return min(lst, key=lambda x: abs(x - target))


def get_full_scale_power_dBm_and_amplitude(desired_power: float, max_amplitude: float = 0.5) -> tuple[int, float]:
    """Get the full_scale_power_dbm and waveform amplitude for the MW FEM to output the specified desired power.

    The keyword `full_scale_power_dbm` is the maximum power of normalized pulse waveforms in [-1,1].
    To convert to voltage:
        power_mw = 10**(full_scale_power_dbm / 10)
        max_voltage_amp = np.sqrt(2 * power_mw * 50 / 1000)
        amp_in_volts = waveform * max_voltage_amp
        ^ equivalent to OPX+ amp
    Its range is -11dBm to +16dBm with 3dBm steps.

    Args:
        desired_power (float): Desired output power in dBm.
        max_amplitude (float, optional): Maximum allowed waveform amplitude in V. Default is 0.5V.

    Returns:
        tuple[float, float]: The full_scale_power_dBm and waveform amplitude realizing the desired power.
    """
    allowed_powers = [-11, -8, -5, -2, 1, 4, 7, 10, 13, 16]
    resulting_power = desired_power - 20 * np.log10(max_amplitude)
    if resulting_power < 0:
        full_scale_power_dBm = closest_number(allowed_powers, max(resulting_power + 3, -11))
    else:
        full_scale_power_dBm = closest_number(allowed_powers, min(resulting_power + 3, 16))
    amplitude = 10 ** ((desired_power - full_scale_power_dBm) / 20)
    if -11 <= full_scale_power_dBm <= 16 and -1 <= amplitude <= 1:
        return full_scale_power_dBm, amplitude
    else:
        raise ValueError(
            f"The desired power is outside the specifications ([-11; +16]dBm, [-1; +1]), got ({full_scale_power_dBm}; {amplitude})"
        )


########################################################################################################################
# %%                                    Resonator parameters
########################################################################################################################
# Update frequencies - be aware of coupled ports for bands
# The keyword "band" refers to the following frequency bands:
#   1: (50 MHz - 5.5 GHz)
#   2: (4.5 GHz - 7.5 GHz)
#   3: (6.5 GHz - 10.5 GHz)
# Note that the "coupled" ports O1 & I1, O2 & O3, O4 & O5, O6 & O7, and O8 & I2 must be in the same band.

# Resonator frequency
rr_freq = 4.5 * u.GHz
rr_LO = 4.75 * u.GHz
rr_if = rr_freq - rr_LO  # The intermediate frequency is inferred from the LO and readout frequencies
assert np.abs(rr_if) < 400 * u.MHz, (
    "The resonator intermediate frequency must be within [-400; 400] MHz. \n"
    f"Readout frequency: {rr_freq} \n"
    f"Readout LO frequency: {rr_LO} \n"
    f"Readout IF frequency: {rr_if} \n"
)

# Desired output power in dBm - Must be within [-80, 16] dBm
readout_power = -40
# Get the full_scale_power_dBm and waveform amplitude corresponding to the desired powers
rr_full_scale, rr_amplitude = get_full_scale_power_dBm_and_amplitude(
    readout_power, max_amplitude=0.125 / len(machine.qubits)
)

# Update qubit rr freq and power
for k, qubit in enumerate(machine.qubits.values()):
    qubit.resonator.f_01 = rr_freq  # Resonator frequency optimized for discriminating 0 (|g>) and 1 (|e>)
    qubit.resonator.RF_frequency = qubit.resonator.f_01  # Readout frequency
    qubit.resonator.opx_output.full_scale_power_dbm = rr_full_scale  # Max readout power in dBm
    qubit.resonator.opx_output.upconverter_frequency = rr_LO  # Readout up-converter frequency
    qubit.resonator.opx_input.band = get_band(rr_LO)  # Readout band for the up-conversion
    qubit.resonator.opx_output.band = get_band(rr_LO)  # Readout band for the down-conversion


########################################################################################################################
# %%                                    Qubit parameters
########################################################################################################################
# The keyword "band" refers to the following frequency bands:
#   1: (50 MHz - 5.5 GHz)
#   2: (4.5 GHz - 7.5 GHz)
#   3: (6.5 GHz - 10.5 GHz)
# Note that the "coupled" ports O1 & I1, O2 & O3, O4 & O5, O6 & O7, and O8 & I2 must be in the same band.

# Qubit drive frequency
xy_freq = 6.0 * u.GHz
xy_LO = 6.0 * u.GHz
xy_if = xy_freq - xy_LO  # The intermediate frequency is inferred from the LO and qubit frequencies
assert np.abs(xy_if) < 400 * u.MHz, (
    "The xy intermediate frequency must be within [-400; 400] MHz. \n"
    f"Qubit drive frequency: {xy_freq} \n"
    f"Qubit drive LO frequency: {xy_LO} \n"
    f"Qubit drive IF frequency: {xy_if} \n"
)
# Transmon anharmonicity
anharmonicity = 200 * u.MHz

# Desired output power in dBm
drive_power = -10
# Get the full_scale_power_dBm and waveform amplitude corresponding to the desired powers
xy_full_scale, xy_amplitude = get_full_scale_power_dBm_and_amplitude(drive_power)

# Update qubit xy freq and power
for k, qubit in enumerate(machine.qubits.values()):
    qubit.f_01 = xy_freq  # Qubit 0 to 1 (|g> -> |e>) transition frequency
    qubit.xy.RF_frequency = qubit.f_01  # Qubit drive frequency
    qubit.xy.opx_output.full_scale_power_dbm = xy_full_scale  # Max drive power in dBm
    qubit.xy.opx_output.upconverter_frequency = xy_LO  # Qubit drive up-converter frequency
    qubit.xy.opx_output.band = get_band(xy_LO)  # Qubit drive band for the up-conversion
    qubit.grid_location = f"{k},0"  # Qubit grid location for plotting as "column,row"
    qubit.anharmonicity = anharmonicity  # Qubit anharmonicity


########################################################################################################################
# %%                                    Cavity parameters
########################################################################################################################
# Cavity frequencies and parameters
# Bosonic cavities are harmonic oscillators with equally spaced energy levels
# Typical cavity frequencies are in the 6-10 GHz range

cavity_freq = 6.5 * u.GHz  # Cavity frequency
cavity_LO = 6.5 * u.GHz  # Local oscillator frequency (can be same as cavity freq for MW-FEM)
cavity_if = cavity_freq - cavity_LO  # Intermediate frequency
assert np.abs(cavity_if) < 400 * u.MHz, (
    "The cavity intermediate frequency must be within [-400; 400] MHz. \n"
    f"Cavity frequency: {cavity_freq} \n"
    f"Cavity LO frequency: {cavity_LO} \n"
    f"Cavity IF frequency: {cavity_if} \n"
)

# Desired output power in dBm for cavity drive
cavity_drive_power = -10
# Get the full_scale_power_dBm and waveform amplitude corresponding to the desired powers
cavity_full_scale, cavity_amplitude = get_full_scale_power_dBm_and_amplitude(cavity_drive_power)

# Update cavity parameters
for k, (cavity_id, cavity) in enumerate(machine.cavities.items()):
    cavity.frequency = cavity_freq  # Cavity frequency
    cavity.xy.RF_frequency = cavity.frequency  # Cavity drive frequency
    cavity.xy.opx_output.full_scale_power_dbm = cavity_full_scale  # Max cavity drive power in dBm
    cavity.xy.opx_output.upconverter_frequency = cavity_LO  # Cavity drive up-converter frequency
    cavity.xy.opx_output.band = get_band(cavity_LO)  # Cavity drive band for the up-conversion
    # Cavity coherence times (typical values - adjust based on your hardware)
    cavity.T1 = 100 * u.us  # Cavity T1 (energy relaxation time)
    cavity.T2ramsey = 50 * u.us  # Cavity T2* (dephasing time from Ramsey)
    cavity.T2echo = 80 * u.us  # Cavity T2 (dephasing time from echo)
    cavity.grid_location = f"{k},1"  # Cavity grid location for plotting as "column,row"


########################################################################################################################
# %%                                        Pulse parameters
########################################################################################################################
# Update pulses for qubits
for k, q in enumerate(machine.qubits):
    # readout
    machine.qubits[q].resonator.operations["readout"].length = 2.5 * u.us
    machine.qubits[q].resonator.depletion_time = 2.5 * u.us
    machine.qubits[q].resonator.operations["readout"].amplitude = rr_amplitude
    # Qubit saturation
    machine.qubits[q].xy.operations["saturation"].length = 20 * u.us
    machine.qubits[q].xy.operations["saturation"].amplitude = 0.1 * xy_amplitude
    # Single qubit gates - DragCosine
    add_DragCosine_pulses(
        machine.qubits[q],
        amplitude=xy_amplitude,
        length=40,
        anharmonicity=machine.qubits[q].get_reference() + "/anharmonicity",
        alpha=0.0,
        detuning=0,
    )

# Update pulses for cavities
for cavity_id in machine.cavities:
    # Cavity saturation pulse (used for spectroscopy and initial characterization)
    # Unlike transmons, cavities are harmonic oscillators and don't require DRAG corrections
    machine.cavities[cavity_id].xy.operations["saturation"].length = 20 * u.us
    machine.cavities[cavity_id].xy.operations["saturation"].amplitude = 0.1 * cavity_amplitude

########################################################################################################################
# %%                                         Save the updated QUAM
########################################################################################################################
# save into state.json
machine.save()
# Visualize the QUA config and save it
pprint(machine.generate_config())
with open("qua_config.json", "w+") as f:
    json.dump(machine.generate_config(), f, indent=4)

# %%
