[project]
name = "quam-libs"
version = "0.1.0"
dependencies = []

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry.dependencies]
python = ">=3.9, <3.13"
quam = "*"
plotly = "*"
xarray = "*"

[tool.setuptools]
py-modules = []
