config = {
    "version": 1,
    "controllers": {
        "con1": {
            "analog_outputs": {
                1: {"offset": 0.0},
                2: {"offset": 0.0},
                3: {"offset": 0.0},
                4: {"offset": 0.0},
                5: {"offset": 0.0},
                6: {"offset": 0.0},
                7: {"offset": 0.0},
                8: {"offset": 0.0},
            },
            "digital_outputs": {},
            "analog_inputs": {1: {"offset": 0.0, "gain_db": 5}, 2: {"offset": 0.0, "gain_db": 5}},
        },
        "con2": {
            "analog_outputs": {
                5: {"filter": {"feedforward": [1.0, -0.5], "feedback": [0.4]}, "crosstalk": {}, "offset": 0.0},
                6: {"filter": {"feedforward": [1.0, -0.5], "feedback": [0.4]}, "crosstalk": {}, "offset": 0.0},
                7: {"filter": {"feedforward": [1.0, -0.5], "feedback": [0.4]}, "crosstalk": {}, "offset": 0.0},
                3: {"offset": 0.0},
                4: {"offset": 0.0},
                8: {"filter": {"feedforward": [1.0, -0.5], "feedback": [0.5]}, "crosstalk": {}, "offset": 0.0},
            },
            "digital_outputs": {},
            "analog_inputs": {},
        },
    },
    "elements": {
        "qubit0$xy": {
            "operations": {
                "cw": "qubit0$xy$cw$pulse",
                "id": "qubit0$xy$id$pulse",
                "x": "qubit0$xy$x$pulse",
                "y": "qubit0$xy$y$pulse",
                "sx": "qubit0$xy$sx$pulse",
                "sy": "qubit0$xy$sy$pulse",
            },
            "mixInputs": {"I": ("con1", 3), "Q": ("con1", 4), "mixer": "qubit0$xy$mixer", "lo_frequency": 4750000000.0},
            "intermediate_frequency": -180000000,
        },
        "qubit0$z": {"operations": {}, "singleInput": {"port": ("con2", 5)}},
        "qubit0$rr": {
            "operations": {"readout": "qubit0$rr$readout$pulse"},
            "mixInputs": {"I": ("con1", 1), "Q": ("con1", 2), "mixer": "qubit0$rr$mixer", "lo_frequency": 7600000000.0},
            "intermediate_frequency": -200000000,
            "outputs": {"out1": ("con1", 1), "out2": ("con1", 2)},
            "smearing": 0,
            "time_of_flight": 200,
        },
        "qubit1$xy": {
            "operations": {
                "cw": "qubit1$xy$cw$pulse",
                "id": "qubit1$xy$id$pulse",
                "x": "qubit1$xy$x$pulse",
                "y": "qubit1$xy$y$pulse",
                "sx": "qubit1$xy$sx$pulse",
                "sy": "qubit1$xy$sy$pulse",
            },
            "mixInputs": {"I": ("con1", 5), "Q": ("con1", 6), "mixer": "qubit1$xy$mixer", "lo_frequency": 4750000000.0},
            "intermediate_frequency": -80000000,
        },
        "qubit1$z": {"operations": {}, "singleInput": {"port": ("con2", 6)}},
        "qubit1$rr": {
            "operations": {"readout": "qubit1$rr$readout$pulse"},
            "mixInputs": {"I": ("con1", 1), "Q": ("con1", 2), "mixer": "qubit1$rr$mixer", "lo_frequency": 7600000000.0},
            "intermediate_frequency": -60000000,
            "outputs": {"out1": ("con1", 1), "out2": ("con1", 2)},
            "smearing": 0,
            "time_of_flight": 264,
        },
        "qubit2$xy": {
            "operations": {
                "cw": "qubit2$xy$cw$pulse",
                "id": "qubit2$xy$id$pulse",
                "x": "qubit2$xy$x$pulse",
                "y": "qubit2$xy$y$pulse",
                "sx": "qubit2$xy$sx$pulse",
                "sy": "qubit2$xy$sy$pulse",
            },
            "mixInputs": {"I": ("con1", 7), "Q": ("con1", 8), "mixer": "qubit2$xy$mixer", "lo_frequency": 5350000000.0},
            "intermediate_frequency": -80000000,
        },
        "qubit2$z": {
            "operations": {
                "Cz$flux_pulse_control_qubit1": "qubit2$z$Cz$flux_pulse_control_qubit1$pulse",
                "Cz$flux_pulse_control_qubit0": "qubit2$z$Cz$flux_pulse_control_qubit0$pulse",
            },
            "singleInput": {"port": ("con2", 7)},
        },
        "qubit2$rr": {
            "operations": {"readout": "qubit2$rr$readout$pulse"},
            "mixInputs": {"I": ("con1", 1), "Q": ("con1", 2), "mixer": "qubit2$rr$mixer", "lo_frequency": 7600000000.0},
            "intermediate_frequency": 80000000,
            "outputs": {"out1": ("con1", 1), "out2": ("con1", 2)},
            "smearing": 0,
            "time_of_flight": 264,
        },
        "qubit3$xy": {
            "operations": {
                "cw": "qubit3$xy$cw$pulse",
                "id": "qubit3$xy$id$pulse",
                "x": "qubit3$xy$x$pulse",
                "y": "qubit3$xy$y$pulse",
                "sx": "qubit3$xy$sx$pulse",
                "-sx": "qubit3$xy$-sx$pulse",
                "sy": "qubit3$xy$sy$pulse",
                "-sy": "qubit3$xy$-sy$pulse",
                "x_12": "qubit3$xy$x_12$pulse",
            },
            "mixInputs": {"I": ("con2", 3), "Q": ("con2", 4), "mixer": "qubit3$xy$mixer", "lo_frequency": 6000000000.0},
            "intermediate_frequency": -100000000,
        },
        "qubit3$z": {
            "operations": {"Cz$flux_pulse_control_qubit2": "qubit3$z$Cz$flux_pulse_control_qubit2$pulse"},
            "singleInput": {"port": ("con2", 8)},
        },
        "qubit3$rr": {
            "operations": {"readout": "qubit3$rr$readout$pulse"},
            "mixInputs": {"I": ("con1", 1), "Q": ("con1", 2), "mixer": "qubit3$rr$mixer", "lo_frequency": 7600000000.0},
            "intermediate_frequency": 200000000,
            "outputs": {"out1": ("con1", 1), "out2": ("con1", 2)},
            "smearing": 0,
            "time_of_flight": 264,
        },
    },
    "pulses": {
        "const_pulse": {"operation": "control", "length": 1000, "waveforms": {"I": "const_wf", "Q": "zero_wf"}},
        "qubit0$xy$cw$pulse": {
            "operation": "control",
            "length": 100000,
            "waveforms": {"I": "qubit0$xy$cw$wf$I", "Q": "qubit0$xy$cw$wf$Q"},
        },
        "qubit0$xy$id$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit0$xy$id$wf$I", "Q": "qubit0$xy$id$wf$Q"},
        },
        "qubit0$xy$x$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit0$xy$x$wf$I", "Q": "qubit0$xy$x$wf$Q"},
        },
        "qubit0$xy$y$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit0$xy$y$wf$I", "Q": "qubit0$xy$y$wf$Q"},
        },
        "qubit0$xy$sx$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit0$xy$sx$wf$I", "Q": "qubit0$xy$sx$wf$Q"},
        },
        "qubit0$xy$sy$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit0$xy$sy$wf$I", "Q": "qubit0$xy$sy$wf$Q"},
        },
        "qubit0$rr$readout$pulse": {
            "operation": "measurement",
            "length": 3000,
            "digital_marker": "ON",
            "waveforms": {"I": "qubit0$rr$readout$wf$I", "Q": "qubit0$rr$readout$wf$Q"},
            "integration_weights": {
                "iw1": "qubit0$rr$readout$iw1",
                "iw2": "qubit0$rr$readout$iw2",
                "iw3": "qubit0$rr$readout$iw3",
            },
        },
        "qubit1$xy$cw$pulse": {
            "operation": "control",
            "length": 100000,
            "waveforms": {"I": "qubit1$xy$cw$wf$I", "Q": "qubit1$xy$cw$wf$Q"},
        },
        "qubit1$xy$id$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit1$xy$id$wf$I", "Q": "qubit1$xy$id$wf$Q"},
        },
        "qubit1$xy$x$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit1$xy$x$wf$I", "Q": "qubit1$xy$x$wf$Q"},
        },
        "qubit1$xy$y$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit1$xy$y$wf$I", "Q": "qubit1$xy$y$wf$Q"},
        },
        "qubit1$xy$sx$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit1$xy$sx$wf$I", "Q": "qubit1$xy$sx$wf$Q"},
        },
        "qubit1$xy$sy$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit1$xy$sy$wf$I", "Q": "qubit1$xy$sy$wf$Q"},
        },
        "qubit1$rr$readout$pulse": {
            "operation": "measurement",
            "length": 3000,
            "digital_marker": "ON",
            "waveforms": {"I": "qubit1$rr$readout$wf$I", "Q": "qubit1$rr$readout$wf$Q"},
            "integration_weights": {
                "iw1": "qubit1$rr$readout$iw1",
                "iw2": "qubit1$rr$readout$iw2",
                "iw3": "qubit1$rr$readout$iw3",
            },
        },
        "qubit2$xy$cw$pulse": {
            "operation": "control",
            "length": 100000,
            "waveforms": {"I": "qubit2$xy$cw$wf$I", "Q": "qubit2$xy$cw$wf$Q"},
        },
        "qubit2$xy$id$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit2$xy$id$wf$I", "Q": "qubit2$xy$id$wf$Q"},
        },
        "qubit2$xy$x$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit2$xy$x$wf$I", "Q": "qubit2$xy$x$wf$Q"},
        },
        "qubit2$xy$y$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit2$xy$y$wf$I", "Q": "qubit2$xy$y$wf$Q"},
        },
        "qubit2$xy$sx$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit2$xy$sx$wf$I", "Q": "qubit2$xy$sx$wf$Q"},
        },
        "qubit2$xy$sy$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit2$xy$sy$wf$I", "Q": "qubit2$xy$sy$wf$Q"},
        },
        "qubit2$rr$readout$pulse": {
            "operation": "measurement",
            "length": 3000,
            "digital_marker": "ON",
            "waveforms": {"I": "qubit2$rr$readout$wf$I", "Q": "qubit2$rr$readout$wf$Q"},
            "integration_weights": {
                "iw1": "qubit2$rr$readout$iw1",
                "iw2": "qubit2$rr$readout$iw2",
                "iw3": "qubit2$rr$readout$iw3",
            },
        },
        "qubit3$xy$cw$pulse": {
            "operation": "control",
            "length": 100000,
            "waveforms": {"I": "qubit3$xy$cw$wf$I", "Q": "qubit3$xy$cw$wf$Q"},
        },
        "qubit3$xy$id$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit3$xy$id$wf$I", "Q": "qubit3$xy$id$wf$Q"},
        },
        "qubit3$xy$x$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit3$xy$x$wf$I", "Q": "qubit3$xy$x$wf$Q"},
        },
        "qubit3$xy$y$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit3$xy$y$wf$I", "Q": "qubit3$xy$y$wf$Q"},
        },
        "qubit3$xy$sx$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit3$xy$sx$wf$I", "Q": "qubit3$xy$sx$wf$Q"},
        },
        "qubit3$xy$sy$pulse": {
            "operation": "control",
            "length": 20,
            "waveforms": {"I": "qubit3$xy$sy$wf$I", "Q": "qubit3$xy$sy$wf$Q"},
        },
        "qubit3$rr$readout$pulse": {
            "operation": "measurement",
            "length": 3000,
            "digital_marker": "ON",
            "waveforms": {"I": "qubit3$rr$readout$wf$I", "Q": "qubit3$rr$readout$wf$Q"},
            "integration_weights": {
                "iw1": "qubit3$rr$readout$iw1",
                "iw2": "qubit3$rr$readout$iw2",
                "iw3": "qubit3$rr$readout$iw3",
            },
        },
        "qubit2$z$Cz$flux_pulse_control_qubit1$pulse": {
            "operation": "control",
            "length": 36,
            "waveforms": {"single": "qubit2$z$Cz$flux_pulse_control_qubit1$wf"},
        },
        "qubit2$z$Cz$flux_pulse_control_qubit0$pulse": {
            "operation": "control",
            "length": 40,
            "waveforms": {"single": "qubit2$z$Cz$flux_pulse_control_qubit0$wf"},
        },
        "qubit3$z$Cz$flux_pulse_control_qubit2$pulse": {
            "operation": "control",
            "length": 40,
            "waveforms": {"single": "qubit3$z$Cz$flux_pulse_control_qubit2$wf"},
        },
    },
    "waveforms": {
        "zero_wf": {"type": "constant", "sample": 0.0},
        "const_wf": {"type": "constant", "sample": 0.1},
        "qubit0$xy$cw$wf$I": {"type": "constant", "sample": 0.0},
        "qubit0$xy$cw$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit0$xy$id$wf$I": {"type": "constant", "sample": 0.0},
        "qubit0$xy$id$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit0$xy$x$wf$I": {"type": "constant", "sample": 0.05},
        "qubit0$xy$x$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit0$xy$y$wf$I": {"type": "constant", "sample": 0.0},
        "qubit0$xy$y$wf$Q": {"type": "constant", "sample": 0.05},
        "qubit0$xy$sx$wf$I": {"type": "constant", "sample": 0.025},
        "qubit0$xy$sx$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit0$xy$sy$wf$I": {"type": "constant", "sample": 0.0},
        "qubit0$xy$sy$wf$Q": {"type": "constant", "sample": 0.025},
        "qubit0$rr$readout$wf$I": {"type": "constant", "sample": -0.003},
        "qubit0$rr$readout$wf$Q": {"type": "constant", "sample": -0.005},
        "qubit1$xy$cw$wf$I": {"type": "constant", "sample": 0.001},
        "qubit1$xy$cw$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit1$xy$id$wf$I": {"type": "constant", "sample": 0.0},
        "qubit1$xy$id$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit1$xy$x$wf$I": {"type": "constant", "sample": 0.05},
        "qubit1$xy$x$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit1$xy$y$wf$I": {"type": "constant", "sample": 0.0},
        "qubit1$xy$y$wf$Q": {"type": "constant", "sample": 0.05},
        "qubit1$xy$sx$wf$I": {"type": "constant", "sample": 0.025},
        "qubit1$xy$sx$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit1$xy$sy$wf$I": {"type": "constant", "sample": 0.0},
        "qubit1$xy$sy$wf$Q": {"type": "constant", "sample": 0.025},
        "qubit1$rr$readout$wf$I": {"type": "constant", "sample": -0.004},
        "qubit1$rr$readout$wf$Q": {"type": "constant", "sample": -0.003},
        "qubit2$xy$cw$wf$I": {"type": "constant", "sample": 0.002},
        "qubit2$xy$cw$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit2$xy$id$wf$I": {"type": "constant", "sample": 0.0},
        "qubit2$xy$id$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit2$xy$x$wf$I": {"type": "constant", "sample": 0.05},
        "qubit2$xy$x$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit2$xy$y$wf$I": {"type": "constant", "sample": 0.0},
        "qubit2$xy$y$wf$Q": {"type": "constant", "sample": 0.05},
        "qubit2$xy$sx$wf$I": {"type": "constant", "sample": 0.025},
        "qubit2$xy$sx$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit2$xy$sy$wf$I": {"type": "constant", "sample": 0.0},
        "qubit2$xy$sy$wf$Q": {"type": "constant", "sample": 0.025},
        "qubit2$rr$readout$wf$I": {"type": "constant", "sample": -0.00436727115807878},
        "qubit2$rr$readout$wf$Q": {"type": "constant", "sample": 0.002096510112150792},
        "qubit3$xy$cw$wf$I": {"type": "constant", "sample": 0.0025665241787866094},
        "qubit3$xy$cw$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit3$xy$id$wf$I": {"type": "constant", "sample": 0.0},
        "qubit3$xy$id$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit3$xy$x$wf$I": {"type": "constant", "sample": 0.05},
        "qubit3$xy$x$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit3$xy$y$wf$I": {"type": "constant", "sample": 0.0},
        "qubit3$xy$y$wf$Q": {"type": "constant", "sample": 0.05},
        "qubit3$xy$sx$wf$I": {"type": "constant", "sample": 0.025},
        "qubit3$xy$sx$wf$Q": {"type": "constant", "sample": 0.0},
        "qubit3$xy$sy$wf$I": {"type": "constant", "sample": 0.0},
        "qubit3$xy$sy$wf$Q": {"type": "constant", "sample": 0.025},
        "qubit3$rr$readout$wf$I": {"type": "constant", "sample": 0.005},
        "qubit3$rr$readout$wf$Q": {"type": "constant", "sample": -0.006},
        "qubit2$z$Cz$flux_pulse_control_qubit1$wf": {"type": "constant", "sample": 0.06},
        "qubit2$z$Cz$flux_pulse_control_qubit0$wf": {"type": "constant", "sample": 0.07},
        "qubit3$z$Cz$flux_pulse_control_qubit2$wf": {"type": "constant", "sample": 0.06},
    },
    "digital_waveforms": {"ON": {"samples": [[1, 0]]}},
    "integration_weights": {
        "qubit0$rr$readout$iw1": {"cosine": [(1.0, 3000)], "sine": [(-0.0, 3000)]},
        "qubit0$rr$readout$iw2": {"cosine": [(0.0, 3000)], "sine": [(1.0, 3000)]},
        "qubit0$rr$readout$iw3": {"cosine": [(-0.0, 3000)], "sine": [(-1.0, 3000)]},
        "qubit1$rr$readout$iw1": {"cosine": [(1.0, 3000)], "sine": [(-0.0, 3000)]},
        "qubit1$rr$readout$iw2": {"cosine": [(0.0, 3000)], "sine": [(1.0, 3000)]},
        "qubit1$rr$readout$iw3": {"cosine": [(-0.0, 3000)], "sine": [(-1.0, 3000)]},
        "qubit2$rr$readout$iw1": {"cosine": [(1.0, 3000)], "sine": [(-0.0, 3000)]},
        "qubit2$rr$readout$iw2": {"cosine": [(0.0, 3000)], "sine": [(1.0, 3000)]},
        "qubit2$rr$readout$iw3": {"cosine": [(-0.0, 3000)], "sine": [(-1.0, 3000)]},
        "qubit3$rr$readout$iw1": {"cosine": [(1.0, 3000)], "sine": [(-0.0, 3000)]},
        "qubit3$rr$readout$iw2": {"cosine": [(0.0, 3000)], "sine": [(1.0, 3000)]},
        "qubit3$rr$readout$iw3": {"cosine": [(-0.0, 3000)], "sine": [(-1.0, 3000)]},
    },
    "mixers": {
        "qubit0$xy$mixer": [
            {
                "intermediate_frequency": -178185252.42891213,
                "lo_frequency": 4750000000.0,
                "correction": [1.0, 0.0, 0.0, 1.0],
            }
        ],
        "qubit0$rr$mixer": [
            {"intermediate_frequency": -200000000, "lo_frequency": 7600000000.0, "correction": [1.0, 0.0, 0.0, 1.0]}
        ],
        "qubit1$xy$mixer": [
            {"intermediate_frequency": -80000000, "lo_frequency": 4750000000.0, "correction": [1.0, 0.0, 0.0, 1.0]}
        ],
        "qubit1$rr$mixer": [
            {"intermediate_frequency": -60000000, "lo_frequency": 7600000000.0, "correction": [1.0, 0.0, 0.0, 1.0]}
        ],
        "qubit2$xy$mixer": [
            {"intermediate_frequency": -80000000, "lo_frequency": 5350000000.0, "correction": [1.0, 0.0, 0.0, 1.0]}
        ],
        "qubit2$rr$mixer": [
            {"intermediate_frequency": 80000000, "lo_frequency": 7600000000.0, "correction": [1.0, 0.0, 0.0, 1.0]}
        ],
        "qubit3$xy$mixer": [
            {"intermediate_frequency": -100000000, "lo_frequency": 6000000000.0, "correction": [1.0, 0.0, 0.0, 1.0]}
        ],
        "qubit3$rr$mixer": [
            {"intermediate_frequency": 260000000, "lo_frequency": 7600000000.0, "correction": [1.0, 0.0, 0.0, 1.0]}
        ],
    },
    "oscillators": {},
}
