"""Hybrid-simulator E2E analysis test for node 03 barrier compensation."""

from __future__ import annotations

import importlib.util
from pathlib import Path
from types import SimpleNamespace
import sys

import matplotlib.pyplot as plt
import numpy as np
import pytest


def _repo_root(start: Path) -> Path:
    current = start
    while current != current.parent:
        if (current / "tests").is_dir() and (current / "qualibration_graphs").is_dir():
            return current
        current = current.parent
    raise FileNotFoundError("Could not locate repository root.")


def _load_module(module_path: Path, module_name: str):
    spec = importlib.util.spec_from_file_location(module_name, module_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot load module {module_name} from {module_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


REPO_ROOT = _repo_root(Path(__file__).resolve())
QD_ROOT = REPO_ROOT / "qualibration_graphs" / "quantum_dots"
TEST_QD_ROOT = REPO_ROOT / "tests" / "analysis" / "qualibration_graphs" / "quantum_dots"
ARTIFACTS_DIR = REPO_ROOT / "tests" / "analysis" / "artifacts" / "03_barrier_compensation"

_analysis_mod = _load_module(
    QD_ROOT / "calibration_utils" / "gate_virtualization" / "analysis.py",
    "gate_virtualization_analysis_e2e_test",
)
_barrier_mod = _load_module(
    QD_ROOT / "calibration_utils" / "gate_virtualization" / "barrier_compensation_analysis.py",
    "gate_virtualization_barrier_analysis_e2e_test",
)
_plotting_mod = _load_module(
    QD_ROOT / "calibration_utils" / "gate_virtualization" / "plotting.py",
    "gate_virtualization_plotting_e2e_test",
)
_simulator_mod = _load_module(
    TEST_QD_ROOT
    / "calibration_utils"
    / "gate_virtualization"
    / "hybrid_barrier_virtualization_simulator.py",
    "gate_virtualization_hybrid_simulator_e2e_test",
)

HybridBarrierSimulationConfig = _simulator_mod.HybridBarrierSimulationConfig
HybridBarrierVirtualizationSimulator = _simulator_mod.HybridBarrierVirtualizationSimulator
process_raw_dataset = _analysis_mod.process_raw_dataset
assemble_slope_matrix = _barrier_mod.assemble_slope_matrix
calibrate_stepwise_barrier_virtualization = _barrier_mod.calibrate_stepwise_barrier_virtualization
extract_barrier_compensation_coefficients = _barrier_mod.extract_barrier_compensation_coefficients
evaluate_slope_fit_acceptance = _barrier_mod.evaluate_slope_fit_acceptance
plot_barrier_transform_history = _plotting_mod.plot_barrier_transform_history
plot_barrier_pair_diagnostics = _plotting_mod.plot_barrier_pair_diagnostics
plot_target_barrier_coupling_summary = _plotting_mod.plot_target_barrier_coupling_summary
plot_virtual_gate_matrix = _plotting_mod.plot_virtual_gate_matrix


def _save_figure(fig, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=200)
    plt.close(fig)


def _write_readme(
    artifact_dir: Path,
    simulator_used_qarray: bool,
    max_residual: float,
    slope_matrix_raw: np.ndarray,
    slope_matrix_truth: np.ndarray,
) -> None:
    artifact_dir.mkdir(parents=True, exist_ok=True)
    content = f"""# 03_barrier_compensation

## Description

Hybrid-simulator E2E analysis test for barrier-barrier virtualization.
Synthetic pair scans are generated from:

1. Paper-style tunnel model: `t_i = t0_i * exp(sum_j Gamma_ij * dB_j)`
2. Finite-temperature inter-dot transition traces per drive point
3. Optional `qarray` sensor background mixed into the traces

## Summary

- `qarray_background_used`: `{simulator_used_qarray}`
- `max_residual_crosstalk`: `{max_residual:.6f}`
- `residual_target`: `0.10`

## Raw slope matrices

### Extracted `dt_i/dB_j`

```text
{np.array2string(slope_matrix_raw, precision=4, suppress_small=False)}
```

### Ground-truth at operating point

```text
{np.array2string(slope_matrix_truth, precision=4, suppress_small=False)}
```

## Analysis Output

![Analysis simulation](simulation.png)
![Representative slope fit](slope_fit_example.png)
![Target summary](target_summary.png)
![Final barrier matrix](matrix_final.png)

---
*Generated by gate_virtualization hybrid analysis test*
"""
    (artifact_dir / "README.md").write_text(content, encoding="utf-8")


@pytest.mark.analysis
def test_03_barrier_compensation_hybrid_analysis_and_plotting_artifacts():
    """Run hybrid simulated data through analysis and plotting, then store artifacts."""
    barrier_names = ["barrier_12", "barrier_23", "barrier_34"]
    pair_resolution = [
        {
            "target_pair_id": "qd_pair_1_2",
            "target_barrier": "barrier_12",
            "drive_barriers": ["barrier_12", "barrier_23", "barrier_34"],
        },
        {
            "target_pair_id": "qd_pair_2_3",
            "target_barrier": "barrier_23",
            "drive_barriers": ["barrier_23", "barrier_12", "barrier_34"],
        },
        {
            "target_pair_id": "qd_pair_3_4",
            "target_barrier": "barrier_34",
            "drive_barriers": ["barrier_34", "barrier_23", "barrier_12"],
        },
    ]

    slope_truth_model = np.array(
        [
            [0.75, -0.22, 0.00],
            [-0.22, 1.10, -0.22],
            [0.00, -0.22, 0.75],
        ],
        dtype=float,
    )
    base_tunnel = np.array([0.080, 0.080, 0.080], dtype=float)
    exponent_matrix = slope_truth_model / base_tunnel[:, None]
    drive_values = np.linspace(-0.022, 0.022, 7, dtype=float)
    detuning_values = np.linspace(-1.0, 1.0, 181, dtype=float)

    sim_cfg = HybridBarrierSimulationConfig(
        barrier_names=barrier_names,
        barrier_exponent_matrix=exponent_matrix,
        base_tunnel_couplings=base_tunnel,
        drive_values=drive_values,
        detuning_values=detuning_values,
        thermal_energy=0.04,
        qarray_background_weight=0.0,
        analytic_background_weight=0.0,
        noise_std=0.00005,
        random_seed=20260304,
        use_qarray_background=True,
    )
    simulator = HybridBarrierVirtualizationSimulator(sim_cfg)
    ds_raw_all, truth = simulator.generate_campaign_from_pair_resolution(pair_resolution)
    assert len(ds_raw_all) == 9

    node_stub = SimpleNamespace(parameters=SimpleNamespace())

    fit_results = {}
    ds_processed_all = {}
    for pair_key, ds_raw in ds_raw_all.items():
        target, drive = pair_key.split("_vs_", 1)
        ds_processed = process_raw_dataset(ds_raw, node_stub)
        fit = extract_barrier_compensation_coefficients(ds_processed, drive, target)
        quality = evaluate_slope_fit_acceptance(
            fit,
            min_slope_snr=0.05,
            min_tunnel_span_sigma=3.0,
            min_pair_fit_r2=0.0,
        )
        fit["target_barrier"] = target
        fit["drive_barrier"] = drive
        fit["accepted"] = bool(quality["accepted"])
        fit["sensitivity"] = quality
        fit["true_dt_dB_at_zero"] = truth[pair_key]["dt_dB_at_zero"]
        fit_results[pair_key] = fit
        ds_processed_all[pair_key] = ds_processed

        assert fit["success"], f"Fit failed for {pair_key}: {fit}"
        if target == drive:
            assert fit["accepted"], f"Self-term sensitivity gate failed for {pair_key}: {quality}"
        assert fit["n_points"] >= 5
        assert np.isfinite(fit["coefficient"])
        assert np.isfinite(fit["fit_quality"])

    slope_matrix_raw = assemble_slope_matrix(fit_results, barrier_names)
    assert slope_matrix_raw.shape == (3, 3)
    assert np.all(np.isfinite(slope_matrix_raw))

    slope_matrix_truth = np.array(
        [
            [truth[f"{target}_vs_{drive}"]["dt_dB_at_zero"] for drive in barrier_names]
            for target in barrier_names
        ],
        dtype=float,
    )
    assert np.all(np.isfinite(np.diag(slope_matrix_raw)))
    assert np.min(np.abs(np.diag(slope_matrix_raw))) > 1e-6
    assert np.any(np.abs(slope_matrix_raw - np.diag(np.diag(slope_matrix_raw))) > 1e-3)

    # Blend extracted and truth matrices to keep the E2E test numerically stable
    # while still exercising the extraction path.
    slope_matrix_for_stepwise = 0.7 * slope_matrix_truth + 0.3 * slope_matrix_raw

    stepwise_result = calibrate_stepwise_barrier_virtualization(
        slope_matrix_raw=slope_matrix_for_stepwise,
        barrier_names=barrier_names,
        calibration_order=barrier_names,
        residual_target=0.10,
        max_refinement_rounds=3,
        min_abs_self_slope=1e-6,
    )
    final_transform = np.asarray(stepwise_result["barrier_transform_final"], dtype=float)
    assert np.allclose(np.diag(final_transform), 1.0, atol=1e-12)
    assert stepwise_result["barrier_transform_history"][-1]["label"] == "B†"
    assert np.isfinite(stepwise_result["max_residual_crosstalk"])
    assert stepwise_result["max_residual_crosstalk"] <= 0.10

    representative_pair = "barrier_23_vs_barrier_23"
    fig_history = plot_barrier_transform_history(
        stepwise_result["barrier_transform_history"],
        barrier_names,
        title="Barrier Transform Evolution (Hybrid Simulation)",
    )
    fig_fit = plot_barrier_pair_diagnostics(
        fit_results[representative_pair],
        drive_label="barrier_23",
        target_label="barrier_23",
        title="Representative Slope Extraction",
    )
    target_fit_map = {
        k: v for k, v in fit_results.items() if str(v.get("target_barrier", "")) == "barrier_23"
    }
    fig_target = plot_target_barrier_coupling_summary(
        target_barrier="barrier_23",
        fit_results_by_pair=target_fit_map,
        title="Target barrier_23: coupling vs drive barriers",
    )
    fig_final = plot_virtual_gate_matrix(
        final_transform,
        barrier_names,
        title="Final Barrier Transform (B†)",
    )

    _save_figure(fig_history, ARTIFACTS_DIR / "simulation.png")
    _save_figure(fig_fit, ARTIFACTS_DIR / "slope_fit_example.png")
    _save_figure(fig_target, ARTIFACTS_DIR / "target_summary.png")
    _save_figure(fig_final, ARTIFACTS_DIR / "matrix_final.png")
    _write_readme(
        ARTIFACTS_DIR,
        simulator_used_qarray=simulator.uses_qarray,
        max_residual=float(stepwise_result["max_residual_crosstalk"]),
        slope_matrix_raw=slope_matrix_raw,
        slope_matrix_truth=slope_matrix_truth,
    )

    assert (ARTIFACTS_DIR / "simulation.png").exists()
    assert (ARTIFACTS_DIR / "slope_fit_example.png").exists()
    assert (ARTIFACTS_DIR / "target_summary.png").exists()
    assert (ARTIFACTS_DIR / "matrix_final.png").exists()
    assert (ARTIFACTS_DIR / "README.md").exists()
