from qualibrate.core import QualibrationNode
from quam_config import QubitQuam as Quam
from calibration_utils.common_utils.experiment import get_sensors
from calibration_utils.run_video_mode import (
    Parameters,
    create_video_mode,
    get_axis_names_and_validate,
    get_quam_state_path,
)


description = """
        RUN VIDEO MODE — INTERACTIVE CHARGE STABILITY SCANNING

Launches an interactive "video mode" dashboard for live-tuning gate voltages while
continuously re-acquiring and displaying a 2D charge-stability map. Unlike the other
nodes in this codebase, this is not a single QUA sweep: it opens a background web
dashboard (via qua_dashboards) that repeatedly drives the OPX to scan the chosen x/y
gate axes and streams I/Q/amplitude/phase back in near real time, so the axes, span,
and readout can be adjusted live from the browser rather than by re-running the node.

Prerequisites:
    - Having initialized the Quam (quam_config/populate_quam_state_*.py).
    - Sensor-dot readout calibrated (resonator calibration nodes completed).
    - The chosen x/y axes belonging to a single, common VirtualGateSet.
    - (Optional) An external DC source configured if ``dc_control=True`` is used to hold
      the scan center on an external DAC.

Datasets:
    - None. This node does not fetch or store a QUA-acquired ``ds_raw``/``ds_fit``; the
      dashboard's live acquisition is self-contained and not persisted via node.results.

Figures:
    - None generated by the node itself. All visualization happens live in the browser
      dashboard at ``http://localhost:<video_mode_port>``.

State update:
    - Voltage points are set interactively via the dashboard's Virtual Gates editor.
"""


node = QualibrationNode[Parameters, Quam](name="00_run_video_mode", description=description, parameters=Parameters())


# Any parameters that should change for debugging purposes only should go in here
# These parameters are ignored when run through the GUI or as part of a graph
@node.run_action(skip_if=node.modes.external)
def custom_param(node: QualibrationNode[Parameters, Quam]):
    """Allow the user to locally set the node parameters for debugging purposes, or execution in the Python IDE."""
    # You can get type hinting in your IDE by typing node.parameters.
    pass


# Instantiate the QUAM class from the state file
node.machine = Quam.load()


# %% {Run_video_mode}
@node.run_action(skip_if=node.parameters.simulate)
def run_video_mode(node: QualibrationNode[Parameters, Quam]):
    """Run Video Mode directly from Qualibrate by running this node."""

    # Extract the sensors from the node
    sensors = get_sensors(node)

    # Extract the quam state path from the machine, so that
    quam_state_path = get_quam_state_path(node)

    # Number of repetitions per map
    n_avg = node.parameters.num_shots

    # Find the names of the x-axis, y-axis, and the common virtual gate set.
    x_axis_name, y_axis_name, vgs_id = get_axis_names_and_validate(node)

    # Ensure that the machine is ready to track the integrated voltage
    node.machine.reset_voltage_sequence(vgs_id, track_integrated_voltage=True)

    # Extract a list of the readout pulses that are used. If no sensors are specified in the node parameters,
    # then it uses all of them
    readout_pulses = [s.readout_resonator.operations["readout"] for s in sensors]

    # Whether to include DAC control
    dc_control = node.parameters.dc_control

    # The port to open on localhost
    video_mode_port = node.parameters.video_mode_port

    # Whether to compensate per-line. This cannot be changed in the UI
    per_line_compensation = node.parameters.per_line_compensation

    # The result type to display in the UI, which can be I, Q, Amplitude or Phase
    result_type = node.parameters.result_type

    # Extract the desired span and points
    x_span, x_points = node.parameters.x_span, node.parameters.x_points
    y_span, y_points = node.parameters.y_span, node.parameters.y_points

    # Create an instance of the DataAcquirer and open video mode
    create_video_mode(
        machine=node.machine,
        num_software_averages=n_avg,
        log=node.log,
        x_axis_name=x_axis_name,
        y_axis_name=y_axis_name,
        x_span=x_span,
        x_points=x_points,
        y_span=y_span,
        y_points=y_points,
        virtual_gate_id=vgs_id,
        result_type=result_type,
        dc_control=dc_control,
        readout_pulses=readout_pulses,
        save_path=quam_state_path,
        port=video_mode_port,
        # point_duration = node.parameters.hold_duration,
        mid_scan_compensation=per_line_compensation,
    )


# %% {Load_historical_data}
@node.run_action(skip_if=node.parameters.load_data_id is None)
def load_data(node: QualibrationNode[Parameters, Quam]):
    """Load and plot a previously acquired Video Mode dataset."""
    pass


# %% {Save_results}
@node.run_action()
def save_results(node: QualibrationNode[Parameters, Quam]):
    """Save the node results and state."""
    node.save()
