"""Bell state tomography calibration node.

Performs full two-qubit quantum state tomography of a prepared Bell state to assess the
quality of the entangling (CZ) gate, reconstructing the density matrix and extracting
fidelity/entanglement metrics.
"""

# %% {Imports}
from dataclasses import asdict
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr
from qm.qua import *
from qualang_tools.multi_user import qm_session
from qualang_tools.results import progress_counter
from qualibrate import QualibrationNode
from qualibration_libs.data import XarrayDataFetcher
from qualibration_libs.parameters import get_qubit_pairs
from qualibration_libs.runtime import simulate_and_plot
from quam_config import Quam

from calibration_utils.bell_state_tomography import (
    Parameters,
    fit_raw_data,
    log_fitted_results,
    plot_bell_state_tomography,
    process_raw_dataset,
    require_bell_tomography_prerequisites,
)

# %% {Initialisation}
description = """
**BELL STATE TOMOGRAPHY EXPERIMENT**

This experiment performs full quantum state tomography of a two-qubit Bell state in order to
characterize the fidelity and properties of the entangled state generated by an entangling gate
(e.g. CZ).

The sequence prepares a Bell state, applies a complete set of tomography rotations on both qubits,
and measures the resulting expectation values to reconstruct the two-qubit density matrix.

For each tomography setting, we measure:

1. The joint measurement outcomes of the two qubits in the computational basis.

**State tomography:**
To fully reconstruct the two-qubit quantum state, a set of single-qubit pre-measurement rotations
is applied. These rotations map different Pauli operator combinations (I, X, Y, Z) onto the
measurement basis. By repeating the experiment for all required rotation combinations, the full
density matrix of the Bell state can be reconstructed.

The tomography process involves:

1. Preparing both qubits in the ground state |g⟩
2. Creating the Bell state using single-qubit rotations and an entangling gate (e.g. CZ)
3. Applying a complete set of tomography rotations on both qubits
4. Measuring both qubits in the computational basis
5. Reconstructing the two-qubit density matrix from the measured expectation values

The quality of the Bell state is evaluated by extracting quantities such as:

1. State fidelity with respect to the target Bell state
2. Population and coherence terms of the density matrix
3. Entanglement metrics (e.g. concurrence or Bell-state parity)

Prerequisites:
- Calibrated single-qubit gates and readout for both qubits in the pair
- A calibrated entangling macro (``operation``) on each qubit pair
- Two-qubit readout confusion matrix from node 35_two_qubit_confusion_matrix

State update:
- Bell-state fidelity and purity on ``macros[operation].fidelity["Bell_State"]``
  for each successfully analysed pair
"""

# Be sure to include [Parameters, Quam] so the node has proper type hinting
node = QualibrationNode[Parameters, Quam](
    name="36_bell_state_tomography",  # Name should be unique
    description=description,  # Describe what the node is doing, which is also reflected in the QUAlibrate GUI
    parameters=Parameters(),  # Node parameters defined under calibration_utils/bell_state_tomography/parameters.py
    machine=Quam.load(),  # Instantiate the QUAM class from the state file
)


# Any parameters that should change for debugging purposes only should go in here
# These parameters are ignored when run through the GUI or as part of a graph
@node.run_action(skip_if=node.modes.external)
def custom_param(node: QualibrationNode[Parameters, Quam]):
    """Set custom parameters for debugging purposes only."""
    # node.parameters.qubit_pairs = ["q1-q2"]
    pass


# %% {Create_QUA_program}
@node.run_action(skip_if=node.parameters.load_data_id is not None)
def create_qua_program(node: QualibrationNode[Parameters, Quam]):  # pylint: disable=too-many-statements
    """Create the sweep axes and generate the QUA program from the pulse sequence and the node parameters."""

    # Get the active qubit pairs from the node and organize them by batches
    node.namespace["qubit_pairs"] = qubit_pairs = get_qubit_pairs(node)
    num_qubit_pairs = len(qubit_pairs)

    # Extract the sweep parameters and axes from the node parameters
    n_avg = node.parameters.num_shots

    operation = node.parameters.operation
    # Each pair needs the CZ macro and a valid readout confusion matrix before running this node.
    require_bell_tomography_prerequisites(qubit_pairs, operation)
    # Register the sweep axes to be added to the dataset when fetching data
    node.namespace["sweep_axes"] = {
        "qubit_pair": xr.DataArray(qubit_pairs.get_names()),
        "n": xr.DataArray(
            np.arange(n_avg),
            attrs={"long_name": "average index"},
        ),
        "tomo_axis_control": xr.DataArray(
            [0, 1, 2],
            attrs={"long_name": "control qubit tomography axis (0=X, 1=Y, 2=Z)"},
        ),
        "tomo_axis_target": xr.DataArray(
            [0, 1, 2],
            attrs={"long_name": "target qubit tomography axis (0=X, 1=Y, 2=Z)"},
        ),
    }

    # The QUA program stored in the node namespace to be transfer to the simulation and execution run_actions
    with program() as node.namespace["qua_program"]:
        n_st = declare_output_stream()
        state_control = [declare(int) for _ in range(num_qubit_pairs)]
        state_target = [declare(int) for _ in range(num_qubit_pairs)]
        state = [declare(int) for _ in range(num_qubit_pairs)]
        state_st_control = [declare_output_stream() for _ in range(num_qubit_pairs)]
        state_st_target = [declare_output_stream() for _ in range(num_qubit_pairs)]
        state_st = [declare_output_stream() for _ in range(num_qubit_pairs)]

        for multiplexed_qubit_pairs in qubit_pairs.batch():
            # Initialize the QPU in terms of flux points (flux tunable transmons and/or tunable couplers)
            for qp in multiplexed_qubit_pairs.values():
                node.machine.initialize_qpu(target=qp.qubit_control)
                node.machine.initialize_qpu(target=qp.qubit_target)
            align()

            n = declare(int)
            tomo_axis_control = declare(int)
            tomo_axis_target = declare(int)

            with for_(n, 0, n < n_avg, n + 1):
                save(n, n_st)
                wait(100)  # I think this is needed this otherwise data is not streaming properly. Need to verify.
                with for_(tomo_axis_control, 0, tomo_axis_control < 3, tomo_axis_control + 1):
                    with for_(tomo_axis_target, 0, tomo_axis_target < 3, tomo_axis_target + 1):

                        # reset
                        for qp in multiplexed_qubit_pairs.values():
                            qp.qubit_control.reset(node.parameters.reset_type, node.parameters.simulate)
                            qp.qubit_target.reset(node.parameters.reset_type, node.parameters.simulate)

                        align()

                        # Bell state
                        for qp in multiplexed_qubit_pairs.values():
                            qp.qubit_control.xy.play("-y90")
                            qp.qubit_target.xy.play("y90")
                            qp.align()
                            qp.macros[operation].apply()
                            qp.qubit_control.xy.play("y90")
                            qp.align()
                            # tomography pulses
                            with if_(tomo_axis_control == 0):  # X axis
                                qp.qubit_control.xy.play("y90")
                            with elif_(tomo_axis_control == 1):  # Y axis
                                qp.qubit_control.xy.play("x90")
                            with if_(tomo_axis_target == 0):  # X axis
                                qp.qubit_target.xy.play("y90")
                            with elif_(tomo_axis_target == 1):  # Y axis
                                qp.qubit_target.xy.play("x90")
                        align()

                        # readout
                        for ii, qp in multiplexed_qubit_pairs.items():
                            qp.qubit_control.readout_state(state_control[ii])
                            qp.qubit_target.readout_state(state_target[ii])
                            assign(state[ii], state_control[ii] * 2 + state_target[ii])
                            save(state_control[ii], state_st_control[ii])
                            save(state_target[ii], state_st_target[ii])
                            save(state[ii], state_st[ii])

            align()

        with stream_processing():
            n_st.save("n")
            for i in range(num_qubit_pairs):
                state_st_control[i].buffer(3).buffer(3).buffer(n_avg).save(f"state_control{i + 1}")
                state_st_target[i].buffer(3).buffer(3).buffer(n_avg).save(f"state_target{i + 1}")
                state_st[i].buffer(3).buffer(3).buffer(n_avg).save(f"state{i + 1}")


# %% {Simulate}
@node.run_action(skip_if=node.parameters.load_data_id is not None or not node.parameters.simulate)
def simulate_qua_program(node: QualibrationNode[Parameters, Quam]):
    """Connect to the QOP and simulate the QUA program"""
    # Connect to the QOP
    qmm = node.machine.connect()
    # Get the config from the machine
    config = node.machine.generate_config()
    # Simulate the QUA program, generate the waveform report and plot the simulated samples
    samples, fig, wf_report = simulate_and_plot(qmm, config, node.namespace["qua_program"], node.parameters)
    # Store the figure, waveform report and simulated samples
    node.results["simulation"] = {"figure": fig, "wf_report": wf_report.to_dict()}


# %% {Execute}
@node.run_action(skip_if=node.parameters.load_data_id is not None or node.parameters.simulate)
def execute_qua_program(node: QualibrationNode[Parameters, Quam]):
    """Connect to the QOP, execute the QUA program and fetch the raw data and store it in a xarray dataset."""
    # Connect to the QOP
    qmm = node.machine.connect()
    # Get the config from the machine
    config = node.machine.generate_config()
    # Execute the QUA program only if the quantum machine is available (this is to avoid interrupting running jobs).
    with qm_session(qmm, config, timeout=node.parameters.timeout) as qm:
        # The job is stored in the node namespace to be reused in the fetching_data run_action
        node.namespace["job"] = job = qm.execute(node.namespace["qua_program"])
        # Display the progress bar
        data_fetcher = XarrayDataFetcher(job, node.namespace["sweep_axes"])
        for dataset in data_fetcher:
            progress_counter(
                data_fetcher.get("n", 0),
                node.parameters.num_shots,
                start_time=data_fetcher.t_start,
            )
        # Display the execution report to expose possible runtime errors
        node.log(job.execution_report())
    # Register the raw dataset
    node.results["ds_raw"] = dataset


# %% {Load_data}
@node.run_action(skip_if=node.parameters.load_data_id is None)
def load_data(node: QualibrationNode[Parameters, Quam]):
    """Load a previously acquired dataset."""
    load_data_id = node.parameters.load_data_id
    # Load the specified dataset
    node.load_from_id(node.parameters.load_data_id)
    node.parameters.load_data_id = load_data_id
    # Get the active qubit pairs from the loaded node parameters
    node.namespace["qubit_pairs"] = get_qubit_pairs(node)


# %% {Analyse_data}
@node.run_action(skip_if=node.parameters.simulate)
def analyse_data(node: QualibrationNode[Parameters, Quam]):
    """Analyse raw data, reconstruct density matrices, log results, set outcomes and store structured results."""
    node.results["ds_raw"] = process_raw_dataset(node.results["ds_raw"], node)
    (
        node.results["ds_fit"],
        node.results["paulis_data"],
        node.results["rhos"],
        fit_results,
    ) = fit_raw_data(node.results["ds_raw"], node)
    node.results["fit_results"] = {k: asdict(v) for k, v in fit_results.items()}
    for qp in node.namespace["qubit_pairs"]:
        node.results[f"{qp.name}_fidelity"] = fit_results[qp.name].fidelity
        node.results[f"{qp.name}_purity"] = fit_results[qp.name].purity
    log_fitted_results(fit_results, log_callable=node.log)
    node.outcomes = {
        qubit_pair_name: ("successful" if fit_result.success else "failed")
        for qubit_pair_name, fit_result in fit_results.items()
    }


# %% {Plot_data}
@node.run_action(skip_if=node.parameters.simulate)
def plot_data(node: QualibrationNode[Parameters, Quam]):
    """Plot Bell state tomography results: 3D city plots, density matrices, and Pauli expectation values."""
    qubit_pairs = node.namespace["qubit_pairs"]
    figures = plot_bell_state_tomography(
        node.results["rhos"],
        node.results["paulis_data"],
        qubit_pairs,
        node,
    )
    for name, fig in figures.items():
        node.results[name] = fig
    plt.show()


# %% {Update_state}
@node.run_action(skip_if=node.parameters.simulate)
def update_state(node: QualibrationNode[Parameters, Quam]):
    """Update the relevant parameters if the qubit pair data analysis was successful."""
    operation = node.parameters.operation
    with node.record_state_updates():
        for qp in node.namespace["qubit_pairs"]:
            if node.outcomes[qp.name] == "failed":
                continue
            node.machine.qubit_pairs[qp.id].macros[operation].fidelity["Bell_State"] = {
                "Fidelity": float(node.results[f"{qp.name}_fidelity"]),
                "Purity": float(node.results[f"{qp.name}_purity"]),
            }


# %% {Save_results}
@node.run_action()
def save_results(node: QualibrationNode[Parameters, Quam]):
    """Save the calibration results."""
    node.save()


# %%
