[project]
name = "quam-config"
version = "0.1.0"
dependencies = [
    "colorama",
]
requires-python = ">=3.9, <3.13"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []