READOUT_RESONATORS_PER_FEED_LINE = 6

NUMBER_OF_QUBITS_W_CHARGE = 6
NUMBER_OF_QUBITS_WO_CHARGE = 0
NUMBER_OF_DRIVE_LINES = 1
NUMBER_OF_QP_INJECTORS = 2
NUMBER_OF_CHARGE_LINES = 2
NUMBER_OF_QUBITS_PER_DRIVE_LINE = NUMBER_OF_QUBITS_W_CHARGE + NUMBER_OF_QUBITS_WO_CHARGE

threads = ["a", "b", "c", "d", "e", "f"]
