READOUT_RESONATORS_PER_FEED_LINE = 6

NUMBER_OF_QUBITS = 6
NUMBER_OF_DRIVE_LINES = 2
NUMBER_OF_QP_INJECTORS = 2
NUMBER_OF_CHARGE_LINES = 2
NUMBER_OF_QUBITS_PER_DRIVE_LINE = 3

threads = ["a", "b", "c", "d", "e", "f"]
